version: '2.2'
services:
  recipecooking:
    depends_on:
         mysqlserver:
          condition: service_healthy
    build:
      context: .
    ports:
      - 8000:8000
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/recipeCooking
    
    volumes:
      - ./:/app
    command: ./mvnw spring-boot:run -Dspring-boot.run.profiles=mysql -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
    
  mysqlserver:
    image: mysql:8.0.23
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=epsi
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=student
      - MYSQL_PASSWORD=epsi
      - MYSQL_DATABASE=recipeCooking
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
volumes:
  mysql_data:
  mysql_config: